module.exports = {
  searchTerms: [
    'landscaping company near Princeton NJ',
    'general contractor near Ewing NJ',
    'roofing contractor near Trenton NJ',
    'plumber near Princeton NJ',
    'electrician near Ewing NJ',
    'hvac contractor near Trenton NJ',
    'home remodeling near Princeton NJ',
    'masonry contractor near Ewing NJ',
    'painting contractor near Trenton NJ',
    'flooring contractor near Princeton NJ',
  ],
  focusFilters: {
    requireWebsite: true,
    excludeNameKeywords: [
      'realtor',
      'realtors',
      'real estate',
      'brokerage',
      'property management',
      'mls',
      'listing',
      'century 21',
      'berkshire hathaway',
      're/max',
      'kw ',
      'keller williams',
      'planet fitness',
      'orangetheory',
      'lifetime',
      'anytime fitness',
      'crunch fitness',
      'd1 training',
      'ferguson',
      'home depot',
      'lowes',
      'walmart',
      'target',
    ],
    excludeWebsiteKeywords: [
      'realtor.com',
      'zillow.com',
      'redfin.com',
      'loopnet.com',
      'apartments.com',
      'homes.com',
      'trulia.com',
      'yelp.com',
      'facebook.com',
      'instagram.com',
      'linkedin.com',
      'maps.google.',
      'google.com/maps',
    ],
  },
  // Legacy chain list kept for scraper-level filtering hooks.
  chainKeywords: [
    'mcdonald', 'starbucks', 'subway', 'dunkin', 'cvs', 'walgreens',
    'target', 'walmart', 'home depot', 'lowes', 'burger king', 'wendy',
    'chick-fil', 'domino', 'pizza hut', 'h&r block', 'great clips',
  ],
  maxResultsPerTerm: 20,
  outputDir: './output',
};
